package com.bracketcove.constants

const val KEY_TYPE = "key_type"
const val KEY_STATUS = "status"

const val KEY_DEST_ADDRESS = "KEY_DEST_ADDRESS"
const val KEY_DEST_LAT = "KEY_DEST_LAT"
const val KEY_DEST_LON = "KEY_DEST_LON"

const val KEY_DRIVER_ID = "KEY_DRIVER_ID"
const val KEY_DRIVER_LAT = "KEY_DRIVER_LAT"
const val KEY_DRIVER_LON = "KEY_DRIVER_LON"
const val KEY_DRIVER_AVATAR_URL = "KEY_DRIVER_AVATAR_URL"
const val KEY_DRIVER_NAME = "KEY_DRIVER_NAME"

const val KEY_PASSENGER_ID = "KEY_PASSENGER_ID"
const val KEY_PASSENGER_LAT = "KEY_PASSENGER_LAT"
const val KEY_PASSENGER_LON = "KEY_PASSENGER_LON"
const val KEY_PASSENGER_AVATAR_URL = "KEY_PASSENGER_AVATAR_URL"
const val KEY_PASSENGER_NAME = "KEY_PASSENGER_NAME"
const val KEY_PASSENGER_ADDRESS = "KEY_PASSENGER_ADDRESS"


const val STREAM_USER_ID = "id"
const val STREAM_USER_ROLE = "role"
const val STREAM_USER_ROLE_ADMIN = "admin"
const val STREAM_CHANNEL_TYPE_MESSAGING = "messaging"

const val FILTER_UPDATED_AT = "updatedAt"
